# Generated by Django 5.0 on 2024-01-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='task_catagory',
            field=models.CharField(default='programming', max_length=50),
        ),
    ]
