# Generated by Django 5.0 on 2024-01-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0002_task_model_task_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='task_catagory',
        ),
        migrations.AddField(
            model_name='task_model',
            name='task_catagory',
            field=models.ManyToManyField(to='category.catagory_model'),
        ),
    ]
